WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT    = _{ "(*" ~ (!("*") ~ ANY)* ~ "*)" }

// and_op = @{ "&&" }
// or_op  = @{ "||" }
// arrow  = @{ "->" }
// dif    = @{ "<>" }
// cons   = @{ "::" }
// eq     = @{ "=" }
// colon  = @{ ":" }
// semi   = @{ ";" }
// dot    = @{ "." }
// minus  = @{ "-" }
// plus   = @{ "+" }
// mul    = @{ "*" }
// mod_op = @{ "%" }
// div    = @{ "/" }

// ident       = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
// longident   = @{ ident ~ ("." ~ ident)* }
// capitalized = @{ ASCII_ALPHA_UPPER ~ (ASCII_ALPHANUMERIC | "_")* }

/// /
// CONSTANTS
/// /

// int = @{ ASCII_DIGIT+ }
// string = @{ "\"" ~ (("\\\"" | !"\"" ~ ANY))* ~ "\"" }

// constant = { int | string }

/// /
// PATTERNS
/// /

// simple_pattern = {
// "_"
// | ident
// | constant
// | "(" ~ pattern ~ ")"
// | constructor_pattern
// | lst_pattern
// | empty_tuple_pattern
// }

// constructor_pattern = { capitalized ~ simple_pattern }
// lst_cons_pattern    = { simple_pattern ~ "::" ~ pattern }
// lst_pattern         = {
// "[" ~ "]"
// | "[" ~ pattern ~ (";" ~ pattern)* ~ ";"? ~ "]"
// }
// pattern             = { simple_pattern | tuple_pattern | lst_cons_pattern }

// tuple_pattern       = {
// simple_pattern ~ "," ~ pattern ~ ("," ~ pattern)*
// }
// empty_tuple_pattern = { "(" ~ ")" }

// /// /
// // EXPRESSIONS
// /// /

// comma = { "," }

// infix_op = _{
// comma
// | semi
// | or_op
// | and_op
// | eq
// | dif
// | cons
// | plus
// | minus
// | mul
// | div
// | mod_op
// }

// expr = { let_expr | simple_expr | function_call | tuple | match_expr | lst_cons_expr }

// lst_cons_expr = { simple_expr ~ "::" ~ expr }

// lst_expr = {
// "[" ~ "]"
// | "[" ~ expr ~ (";" ~ expr)* ~ ";"? ~ "]"
// }

// match_expr = {
// "match" ~ expr ~ "with" ~ case_lst
// }

// case_lst = {
// ("|" ~ case)+
// | case ~ ("|" ~ case)*
// }

// case = {
// pattern ~ ("|" ~ pattern)* ~ "->" ~ expr
// }

// simple_expr = {
// constant
// | longident
// | "(" ~ expr ~ ")"
// | lst_expr
// }

// function_call = {
// simple_expr ~ expr
// }

// tuple = {
// simple_expr ~ "," ~ expr ~ ("," ~ expr)*
// }

/// /
// LET BINDINGS
/// /

// let_binding = {
// "let" ~ rec_flag? ~ value_binding+
// }

// value_binding = {
// pattern
// | "(" ~ pattern ~ (colon ~ typexpr)? ~ eq ~ expr
// }

// simple_type = {
// "_"
// | longident
// | "(" ~ typexpr ~ ")"
// }

// arglabel = {
// "?"? ~ ident
// }

// arrow_type = {
// (arglabel ~ colon)? ~ simple_type ~ arrow ~ typexpr
// }

// tuple_type = {
// simple_type ~ ("*" ~ typexpr)*
// }

// typeconstr = {
// longident
// }

// typeconstr_expr = {
// simple_type ~ typeconstr
// | "(" ~ simple_type ~ ("," ~ typexpr)* ~ ")" ~ typeconstr
// }

// typexpr = {
// typeconstr_expr
// | arrow_type
// | tuple_type
// | simple_type
// }

// let_expr = { "let" ~ rec_flag? ~ pattern ~ "=" ~ expr ~ "in" ~ expr }
// rec_flag = { "rec" }
// let_def  = { "let" ~ rec_flag? ~ pattern ~ "=" ~ expr }

shebang = @{ "#!" ~ (!NEWLINE ~ ANY)* ~ NEWLINE }

compilation_unit = {
    shebang? ~ _structure?
}

_structure = {
    ";;"+
  | ";;"* ~ (structure_item | toplevel_directive | expression_item) ~ ((";;"* ~ (structure_item | toplevel_directive)) | (";;"+ ~ expression_item))* ~ ";;"*
}

expression_item = {
    sequence_expression ~ item_attribute*
}

_signature = {
    ";;"+
  | (";;"* ~ signature_item)+ ~ ";;"*
}

toplevel_directive = {
    directive ~ (constant | value_path | module_path)?
}

structure_item = {
    value_definition
  | external
  | type_definition
  | exception_definition
  | module_definition
  | module_type_definition
  | open_module
  | include_module
  | class_definition
  | class_type_definition
  | floating_attribute
  | item_extension
}

value_definition = {
    ("let" ~ attribute? ~ "rec"? | let_operator) ~ (let_binding ~ (("and" | let_and_operator) ~ let_binding)*)
}

let_binding = {
    binding_pattern ~ (_parameter* ~ polymorphic_typed? ~ (":>" ~ type)? ~ "=" ~ sequence_expression)? ~ item_attribute*
}

_parameter = {
    parameter
  | parenthesized_abstract_type
}

parameter = {
    simple_pattern
  | ("~" | "?") ~ simple_value_pattern
  | labelled_start ~ simple_pattern
  | ("~" | "?") ~ "(" ~ simple_value_pattern ~ typed? ~ ("=" ~ sequence_expression)? ~ ")"
  | labelled_start ~ "(" ~ pattern ~ typed? ~ ("=" ~ sequence_expression) ~ ")"
}

labelled_start = @{ label ~ ":" }

external = {
    "external" ~ attribute? ~ value_name ~ polymorphic_typed ~ "=" ~ string+ ~ item_attribute*
}

type_definition = {
    "type" ~ attribute? ~ "nonrec"? ~ type_binding ~ ("and" ~ type_binding)*
}

type_binding = {
    type_params? ~ type_binding_kind ~ item_attribute*
}

type_binding_kind = {
    type_constructor ~ type_equation? ~ ("=" ~ "private"? ~ (variant_declaration | record_declaration))? ~ type_constraint*
  | type_constructor_path ~ "+=" ~ "private"? ~ variant_declaration
}

type_params = {
    type_param
  | "(" ~ type_param ~ ("," ~ type_param)* ~ ")"
}

type_param = {
    (("+" ~ "!"?) | ("-" ~ "!"?) | ("!" ~ ("+" | "-")?))? ~ (type_variable | "_")
}

type_equation = {
    ("=" ~ ":=") ~ "private"? ~ type
}

variant_declaration = {
    ("|" ~ constructor_declaration)+
  | constructor_declaration ~ ("|" ~ constructor_declaration)
}

constructor_declaration = {
    (constructor_name | (("[" ~ "]") | ("(" ~ ")") | ("true") | ("false"))) ~ ("of" ~ constructor_argument ~ ":" ~ (type_variable+ ~ ".")? ~ (constructor_argument ~ "->")? ~ simple_type ~ simple_type)?
}

constructor_argument = {
    simple_type ~ ("*" ~ simple_type)*
  | record_declaration
}

record_declaration = {
    "{" ~ field_declaration ~ (";" ~ field_declaration)* ~ ";"? ~ "}"
}

field_declaration = {
    "mutable"? ~ field_name ~ polymorphic_typed
}

type_constraint = {
    "constraint" ~ type ~ "=" ~ type
}

exception_definition = {
    "exception" ~ attribute? ~ constructor_declaration ~ item_attribute*
}

module_definition = {
    "module" ~ attribute? ~ "rec"? ~ module_binding ~ ("and" ~ module_binding)*
}

module_binding = {
    (module_name | "_") ~ module_parameter* ~ module_typed? ~ (("=" | ":=") ~ module_expression)? ~ item_attribute*
}

module_parameter = {
    "(" ~ ((module_name | "_") ~ module_typed)? ~ ")"
}

module_type_definition = {
    "module" ~ "type" ~ attribute? ~ module_type_name ~ (("=" | ":=") ~ module_type)? ~ item_attribute*
}

open_module = {
    "open" ~ "!"? ~ attribute? ~ module_expression ~ item_attribute*
}

include_module = {
    "include" ~ attribute? ~ module_expression ~ item_attribute*
}

class_definition = {
    "class" ~ attribute? ~ class_binding ~ ("and" ~ class_binding)*
}

class_binding = {
    "virtual"? ~ ("[" ~ type_param ~ ("," ~ type_param)* ~ "]")? ~ class_name ~ parameter* ~ class_typed? ~ ("=" ~ class_expression)? ~ item_attribute*
}

class_type_definition = {
    "class" ~ "type" ~ attribute? ~ class_type_binding ~ ("and" ~ class_type_binding)*
}

class_type_binding = {
    "virtual"? ~ ("[" ~ type_param ~ ("," ~ type_param)* ~ "]")? ~ class_type_name ~ "=" ~ simple_class_type ~ item_attribute*
}

signature_item = {
    value_specification
  | external
  | type_definition
  | exception_definition
  | module_definition
  | module_type_definition
  | open_module
  | include_module_type
  | class_definition
  | class_type_definition
  | floating_attribute
  | item_extension
}

value_specification = {
    "val" ~ attribute? ~ value_name ~ polymorphic_typed ~ item_attribute*
}

include_module_type = {
    "include" ~ attribute? ~ module_type ~ item_attribute?
}

module_typed = {
    ":" ~ module_type
}

simple_module_type = {
    module_type_path
  | signature
  | parenthesized_module_type
}

module_type = {
    simple_module_type
  | module_type_constraint
  | module_type_of
  | functor_type
  | extension
}

signature = {
    "sig" ~ _signature? ~ "end"
}

module_type_constraint_kind = {
    constrain_type
  | constrain_module
  | constrain_module_type
}

module_type_constraint = {
    simple_module_type ~ "with" ~ module_type_constraint_kind ~ ("and" ~ module_type_constraint_kind)
}

constrain_type = {
    "type" ~ type_params? ~ type_constructor_path ~ type_equation ~ type_constraint*
}

constrain_module = {
    "module" ~ module_path ~ ("=" | ":=") ~ extended_module_path
}

module_type_of = {
    "module" ~ "type" ~ module_type_path ~ ("=" | ":=") ~ module_type
}

functor_type = {
    functor_type_lhs ~ "->" ~ module_type
}

functor_type_lhs = {
    "functor" ~ module_parameter*
  | simple_module_type
}

parenthesized_module_type = {
    "(" ~ module_type ~ ")"
}

simple_module_expression = {
  
  | parenthesized_module_expression
  | packed_module
  | extension
}

module_expression = {
    simple_module_expression
  | typed_module_expression
  | module_path
  | structure
  | functor
  | module_application
}

structure = {
    "struct" ~ _structure? ~ "end"
}

functor = {
    "functor" ~ module_parameter+ ~ "->" ~ module_expression
}

module_application = {
    simple_module_expression ~ (module_expression | ("(" ~ ")"))
}

typed_module_expression = {
    simple_module_expression ~ module_typed
}

packed_module = {
    "val" ~ expression ~ module_typed? ~ (":>" ~ module_type)?
}

parenthesized_module_expression = {
    "(" ~ module_expression ~ ")"
}

class_typed = {
    ":" ~ class_type
}

simple_class_type = {
    class_type_path
  | instantiated_class_type
  | class_body_type
  | let_open_class_type
  | extension
}

class_type = {
    simple_class_type
  | class_function_type
}

instantiated_class_type = {
    "[" ~ type ~ ("," ~ type)* ~ "]" ~ class_type_path
}

class_body_type = {
    "object" ~ ("(" ~ type ~ ")")? ~ (class_field_specification | floating_attribute)* ~ "end"
}

class_field_specification = {
    inheritance_specification
  | instance_variable_specification
  | method_specification
  | type_parameter_constraint
  | item_extension
}

inheritance_specification = {
    "inherit" ~ simple_class_type ~ item_attribute*
}

virt_mut_spec = {
    "virtual" ~ "mutable"?
  | "mutable" ~ "virtual"?
}

instance_variable_specification = {
    "val" ~ virt_mut_spec? ~ instance_variable_name ~ typed ~ item_attribute*
}

virt_priv_spec = {
    "virtual" ~ "private"?
  | "private" ~ "virtual"?
}

method_specification = {
    "method" ~ virt_priv_spec? ~ method_name ~ polymorphic_typed ~ item_attribute*
}

type_parameter_constraint = {
    "constraint" ~ type ~ "=" ~ type ~ item_attribute*
}

let_open_class_type = {
    "let" ~ open_module ~ "in" ~ simple_class_type
}

class_function_type = {
    argument_type ~ "->" ~ class_type
}

simple_class_expression = {
    class_path
  | instantiated_class
  | object_expression
  | typed_class_expression
  | parenthesized_class_expression
  | extension
}

class_expression = {
    simple_class_expression
  | class_function
  | class_application
  | let_class_expression
  | let_open_class_expression
}

instantiated_class = {
    "[" ~ type ~ ("," ~ type)* ~ "]" ~ class_path
}

typed_class_expression = {
    "(" ~ simple_class_expression ~ class_typed ~ ")"
}

class_function = {
    "fun" ~ parameter+ ~ "->" ~ class_expression
}

class_application = { simple_class_expression ~ argument+ }

let_class_expression = {
    value_definition ~ "in" ~ class_expression
}

class_field = {
    inheritance_definition
  | instance_variable_definition
  | method_definition
  | type_parameter_constraint
  | class_initializer
  | item_extension
}

inheritance_definition = {
    "inherit" ~ "!"? ~ class_expression ~ ("as" ~ value_pattern)? ~ item_attribute*
}

instance_variable_definition = {
    "val" ~ "!"? ~ virt_mut_spec? ~ instance_variable_name ~ typed? ~ (":>" ~ type)? ~ ("=" ~ sequence_expression)? ~ item_attribute*
}

method_definition = {
    "method" ~ "!"? ~ virt_priv_spec? ~ method_name ~ parameter* ~ polymorphic_typed? ~ ("=" ~ sequence_expression)? ~ item_attribute*
}

class_initializer = {
    "initializer" ~ sequence_expression ~ item_attribute*
}

let_open_class_expression = {
    "let" ~ open_module ~ "in" ~ class_expression
}

parenthesized_class_expression = { "(" ~ class_expression ~ ")" }

typed             = { ":" ~ type }
simple_typed      = { ":" ~ simple_type }
polymorphic_typed = { ":" ~ _polymorphic_type }

_polymorphic_type = { polymorphic_type | type }
polymorphic_type  = {
    (type_variable+ | abstract_type) ~ "." ~ type
}

abstract_type = {
    "type" ~ type_constructor+
}

parenthesized_abstract_type = {
    "(" ~ abstract_type ~ ")"
}

simple_type = {
    type_variable
  | type_constructor_path
  | local_open_type
  | polymorphic_variant_type
  | package_type
  | hash_type
  | object_type
  | parenthesized_type
  | extension
}

type = {
    simple_type
  | tuple_type
  | constructed_type
  | function_type
  | function_type
  | aliased_type
}

function_type = { argument_type ~ "->" ~ type }

argument_type = {
    simple_type ~ proper_tuple_type ~ labeled_argument_type
}

labeled_argument_type = {
    "?"? ~ label_name ~ ":" ~ argument_type
}

proper_tuple_type = { simple_type ~ "*" ~ proper_tuple_type_rhs }

labeled_tuple_type = {
    labeled_tuple_element_type ~ "*" ~ tuple_type_rhs
}

labeled_tuple_element_type = {
    label_name ~ ":" ~ simple_type
}

proper_tuple_type_rhs = {
    simple_type ~ ("*" ~ proper_tuple_type_rhs)?
}

tuple_type_rhs = {
    (simple_type | labeled_tuple_element_type) ~ ("*" ~ tuple_type_rhs)?
}

tuple_type = { labeled_tuple_type | proper_tuple_type }

constructed_type = {
    (simple_type | ("(" ~ type ~ ("," ~ type)*)) ~ type_constructor_path
}

aliased_type = { simple_type ~ "as" ~ type_variable }

local_open_type = {
    extended_module_path ~ "." ~ (("(" ~ type ~ ")") | package_type | polymorphic_variant_type)
}

polymorphic_variant_type = {
    "[" ~ tag_specification ~ "]"
  | "[" ~ tag_spec? ~ "|" ~ tag_spec ~ ("|" ~ tag_spec)* ~ "]"
  | "[>" ~ "]"
  | "[>" ~ tag_spec? ~ "|" ~ tag_spec ~ ("|" ~ tag_spec)* ~ "]"
  | "[<" ~ "]"
  | "[<" ~ tag_spec? ~ "|" ~ tag_spec ~ ("|" ~ tag_spec)* ~ "]"
}

tag_spec = {
    type
  | tag_specification
}

tag_specification = {
    tag ~ ("of" ~ "&"? ~ type ~ ("&" ~ type)*)?
}

package_type = {
    "module" ~ attribute? ~ module_type
}

object_type_field_kind = {
    method_type
  | simple_type
}

object_type_field_kind_lst = {
    object_type_field_kind ~ (";" ~ object_type_field_kind)*
}

object_type = {
    "<" ~ ">"
  | "<" ~ ".." ~ ">"
  | "<" ~ (object_type_field_kind_lst ~ (";" ~ ".."?)?) ~ ">"
}

method_type = {
    method_name
  | polymorphic_typed
}

hash_type = {
    (simple_type | ("(" ~ type ~ ("," ~ type)* ~ ")"))? ~ "#" ~ class_type_path
}

parenthesized_type = { "(" ~ type ~ ")" }

simple_expression = {
    array_expression
  | assert_expression
  | bigarray_get_expression
  | coercion_expression
  | constant
  | constructor_path
  | extension
  | for_expression
  | fun_expression
  | function_expression
  | hash_expression
  | if_expression
  | labeled_tuple_element
  | lazy_expression
  | let_exception_expression
  | let_module_expression
  | let_open_expression
  | list_expression
  | local_open_expression
  | match_expression
  | method_invocation
  | new_expression
  | object_copy_expression
  | object_expression
  | ocamlyacc_value
  | package_expression
  | parenthesized_expression
  | parenthesized_expression
  | prefix_expression
  | record_expression
  | set_expression
  | tag
  | try_expression
  | typed_expression
  | value_path
  | while_expression
}

sequence_expression = {
    expression
  | sequence_expression_anonymous
}

typed_expression = {
    "(" ~ sequence_expression ~ typed ~ ")"
}

tuple_labelled_start = @{ tuple_label ~ ":" }

labeled_tuple_element = {
    tuple_labelled_start ~ simple_expression
  | "~" ~ "(" ~ label_name ~ typed ~ ")"
  | tuple_label
}

// All your operators
cons_op   = { "::" }
tuple_op  = { "," }
or_op     = { "||" }
and_op    = { "&&" }
eq_op     = { "=" }
ne_op     = { "<>" }
lt_op     = { "<" }
gt_op     = { ">" }
le_op     = { "<=" }
ge_op     = { ">=" }
append_op = { "@" }
concat_op = { "^" }
plus_op   = { "+" }
minus_op  = { "-" }
mult_op   = { "*" }
div_op    = { "/" }
mod_op    = { "mod" }
land_op   = { "land" }
lor_op    = { "lor" }
lxor_op   = { "lxor" }
lsl_op    = { "lsl" }
lsr_op    = { "lsr" }
asr_op    = { "asr" }

infix_operator = {
    "todo"
}

operator = {
    cons_op
  | tuple_op
  | or_op
  | and_op
  | eq_op
  | ne_op
  | lt_op
  | gt_op
  | le_op
  | ge_op
  | append_op
  | concat_op
  | plus_op
  | minus_op
  | mult_op
  | div_op
  | mod_op
  | land_op
  | lor_op
  | lxor_op
  | lsl_op
  | lsr_op
  | asr_op
  | hash_operator
  | infix_operator
}

expression_element = {
    simple_expression // | prefix_operator

  | operator
}

expression = {
    expression_element+
  | field_get_expression
}

list_expression = {
    "[" ~ expr_lst ~ "]"
}

array_expression = {
    "[|" ~ expr_lst ~ "|]"
}

field_expression_lst = {
    field_expression ~ (";" ~ field_expression)* ~ ";"?
}

record_expression_with = {
    "{" ~ expression ~ "with" ~ field_expression_lst ~ "}"
}

record_expression = {
    record_expression_with
  | "{" ~ field_expression_lst ~ "}"
}

expr_lst = { (expression ~ (";" ~ expression))? ~ ";"? }

field_expression = {
    field_path ~ typed? ~ ("=" ~ expression)?
}

application_expression = {
    simple_expression ~ argument+
}

argument = {
    simple_expression
  | labeled_argument
}

labeled_argument = {
    label
  | labelled_start ~ expression
  | ("~" | "?") ~ "(" ~ label_name ~ typed ~ ")"
}

field_get_expression = {
    simple_expression ~ "." ~ field_path
}

array_get_expression = {
    simple_expression ~ "." ~ indexing_operator_path? ~ "(" ~ sequence_expression ~ ")"
}

string_get_expression = {
    simple_expression ~ "." ~ indexing_operator_path? ~ "[" ~ sequence_expression ~ "]"
}

indexing_operator_path        = { "todo" }
hash_operator                 = { "todo" }
field_path                    = { "todo" }
tuple_label                   = { "todo" }
sequence_expression_anonymous = { "todo" }
set_expression                = { "todo" }
if_expression                 = { "todo" }
while_expression              = { "todo" }
for_expression                = { "todo" }
match_expression              = { "todo" }
function_expression           = { "todo" }
fun_expression                = { "todo" }
try_expression                = { "todo" }
assert_expression             = { "todo" }
lazy_expression               = { "todo" }
let_module_expression         = { "todo" }
let_open_expression           = { "todo" }
let_exception_expression      = { "todo" }
constructor_path              = { "todo" }
prefix_expression             = { "todo" }
hash_expression               = { "todo" }
bigarray_get_expression       = { "todo" }
coercion_expression           = { "todo" }
local_open_expression         = { "todo" }
package_expression            = { "todo" }
new_expression                = { "todo" }
object_copy_expression        = { "todo" }
method_invocation             = { "todo" }
object_expression             = { "todo" }
parenthesized_expression      = { "todo" }
ocamlyacc_value               = { "todo" }
attribute                     = { "todo" }
binding_pattern               = { "todo" }
class_name                    = { "todo" }
class_path                    = { "todo" }
class_type_name               = { "todo" }
class_type_path               = { "todo" }
constant                      = { "todo" }
constrain_module_type         = { "todo" }
constructor_name              = { "todo" }
directive                     = { "todo" }
extended_module_path          = { "todo" }
extension                     = { "todo" }
field_name                    = { "todo" }
floating_attribute            = { "todo" }
instance_variable_name        = { "todo" }
item_attribute                = { "todo" }
item_extension                = { "todo" }
label                         = { "todo" }
label_name                    = { "todo" }
let_and_operator              = { "todo" }
let_operator                  = { "todo" }
method_name                   = { "todo" }
module_name                   = { "todo" }
module_path                   = { "todo" }
module_type_name              = { "todo" }
module_type_path              = { "todo" }
pattern                       = { "todo" }
simple_pattern                = { "todo" }
simple_value_pattern          = { "todo" }
string                        = { "todo" }
tag                           = { "todo" }
type_constructor              = { "todo" }
type_constructor_path         = { "todo" }
type_variable                 = { "todo" }
value_name                    = { "todo" }
value_path                    = { "todo" }
value_pattern                 = { "todo" }
